#!/usr/bin/env python
import rospy

from nav_msgs.msg import Path
from nav_msgs.msg import Odometry
from std_msgs.msg import Bool
from geometry_msgs.msg import PoseStamped, PoseArray
import tf


global path_pub
global waypoints


path_pub = rospy.Publisher('/path', Path, queue_size=1)

waypoints = [(0,0),
             (2,0),
             (2.5,0),
             (2.5,2),
             (2,2),
             (0,2)]

def generate_path(section):
    msg = Path()
    msg.header.frame_id = "map"
    msg.header.stamp = rospy.Time.now()
    for wp in section:
        pose = PoseStamped()
        pose.header.frame_id = "map"
        pose.pose.position.x = wp[0]
        pose.pose.position.y = wp[1]
        pose.pose.position.z = 0
        quaternion = tf.transformations.quaternion_from_euler(
            0, 0, 0)
        pose.pose.orientation.x = quaternion[0]
        pose.pose.orientation.y = quaternion[1]
        pose.pose.orientation.z = quaternion[2]
        pose.pose.orientation.w = quaternion[3]
        msg.poses.append(pose)
    return msg


def main():
    for section in zip(waypoints,waypoints[1:]):
        msg = generate_path(section)
        rospy.sleep(1)
        path_pub.publish(msg)
        print 'Moving in section: ', section
        rospy.sleep(5)

if __name__ == '__main__':
    try:
        rospy.init_node('path_node', anonymous=False)
        main()
        rospy.spin()

    except rospy.ROSInterruptException:
        pass
