#!/usr/bin/env python
import rospy

from nav_msgs.msg import Path
from nav_msgs.msg import Odometry
from geometry_msgs.msg import PoseStamped
import tf


global_plan_world_coord = [(0,0),(5,5)]

def publish_path():
    
    global global_plan_world_coord
    path_pub = rospy.Publisher('/path', Path, queue_size=1)
    msg = Path()
    msg.header.frame_id = "/map"
    msg.header.stamp = rospy.Time.now()
    for wp in global_plan_world_coord:
        pose = PoseStamped()
        pose.header.frame_id = "/map"
        pose.pose.position.x = wp[0]
        pose.pose.position.y = wp[1]
        pose.pose.position.z = 0
        quaternion = tf.transformations.quaternion_from_euler(
            0, 0, 0)
        pose.pose.orientation.x = quaternion[0]
        pose.pose.orientation.y = quaternion[1]
        pose.pose.orientation.z = quaternion[2]
        pose.pose.orientation.w = quaternion[3]
        msg.poses.append(pose)
    path_pub.publish(msg)
    print "hi"


if __name__ == '__main__':
    rospy.init_node('path_node')
    # while True:
    publish_path()

